### PR TITLE
add messages for form submission message

### PR DESCRIPTION
**Pull request by NathanQ**
Providing a block to view the app's success message.

### CODE REVIEW

**Comment by stuartaccent** [comment]
Hi @NathanQ, Thanks for this.

How are you finding it? as its very new.

My only observation would be when you have more than one form on the streamfield using this block the message would get repeated in each block. Its fine obviously if you have only one form which i imagine is 99% of the time.

Am wondering if we should be using the messages frameworks at all. Will have a think tonight :)

Stu

**Comment by stuartaccent** [comment]
You've prob already seen but in the short term you could easily override / add another template to do this

Just replace this with your own template or add another to it:

```
WAGTAILSTREAMFORMS_FORM_TEMPLATES = (
    ('streamforms/form_block.html', 'Default Form Template'),
)
```

or add that template path to an app that loads before `wagtailstreamforms`.

http://wagtailstreamforms.readthedocs.io/en/latest/templates.html

**Comment by NathanQ** [comment]
@stuartaccent Your work is exactly(almost) what I was looking for - adding the form to streamfield. I'd worked a little bit with adding the form similarly to Wagtail's SnippetChooserBlock, but I didn't get far. I think needing a separate page model for the form kinda defeats the purpose of the super-nice Wagtail Streamfield.

Re messages: the form sends the submission response by way of messages, so I thought, maybe just add it to your template so the example is a little more clean. What do you think about sending the form submitter to a success page which is what the [form_page_landing.html](http://docs.wagtail.io/en/latest/reference/contrib/forms/index.html) currently is set up to do? 

Thanks again for the really great work!

**Comment by stuartaccent** [comment]
@NathanQ I def agree with the form pages, I know the wagtail guys are looking to do something in this area though not sure what exactly. I know looking at their PR's some want to define the field in the streamfield too. This to me seems a bit odd to me. If you have a large site with lots of forms they would start to get lost. I would rather have a form defined somewhere and reuse it where i want to.

Re messages: Are you happy if I just expand the docs to clarify the current use of messages in that you need to add them somewhere :) I admit i did forget as all our projects use them and have just become a standard thing. The basic template is really only like you say (how to use it) and is pretty pointless and lacks any customisation.

RE: redirecting after a successful post: Would adding a page chooser block to the form which will redirect to that page upon successfully posting fulfil your needs? with a fallback to return to the current page if not set.

Stu

**Comment by NathanQ** [comment]
@stuartaccent 
> RE: redirecting after a successful post... 
What you describe would be amazing!

**Comment by stuartaccent** [comment]
@NathanQ lol, will get you in on the pr's for those. Thanks

**Comment by stuartaccent** [comment]
Once again @NathanQ thanks for the help

**Pull request closed without merging**
